FROM debian:jessie
MAINTAINER Mezuro Team <mezurometrics@gmail.com>

RUN apt-get update

RUN apt-get -y upgrade
RUN apt-get install -y \
  postgresql \
  build-essential \
  ruby \
  bundler \
  ruby-dev \
  rubygems-integration \
  git \
  curl \
  libpq-dev \
  libevent-dev \
  libssl-dev \
  libxml2-dev \
  libxslt1-dev \
  libreadline-dev \
  libsqlite3-dev
RUN gem install fpm-cookery --no-ri --no-rdoc

ADD scripts /root/mezuro/scripts

CMD ["/root/mezuro/scripts/kalibro_configurations/run.sh"]
