FROM ubuntu:14.04
MAINTAINER Mezuro Team <mezurometrics@gmail.com>

RUN apt-get update

RUN apt-get -y upgrade
RUN apt-get install -y build-essential \
  git \
  curl \
  libpq-dev \
  libevent-dev \
  libssl-dev \
  libxml2-dev \
  libxslt1-dev \
  libreadline-dev \
  libsqlite3-dev

ADD src /root/mezuro/src
ADD scripts /root/mezuro/scripts

CMD ["/root/mezuro/scripts/kalibro_configurations/run.sh"]
